name: Alert Completude Bot (every 20min)

on:
  schedule:
    # +2h pour l'heure d'été (basé sur UTC), à adapter pour l'heure d'hiver (+1h)
    - cron: "0,20,40 7-15 * * 1-5"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install playwright

      - name: Install Playwright Browsers
        run: |
          python -m playwright install chromium
          python -m playwright install-deps
      
      - name: Run the script
        env:
          VILLE_CIBLES: ${{ secrets.VILLE_CIBLES }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          ADRESSE_PERSONNELLE: ${{ secrets.ADRESSE_PERSONNELLE }}
          USER_ID: ${{ secrets.USER_ID }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: |
          python alerte_bot.py
